#!/bin/bash

############################## U SCRIPTS ###################################
##                  DanielDAN - danielolszyk1988@gmail.com                ##
##                      This program is Open Source                       ##
############################################################################


# bold=$(tput bold)                   # Text style bold
# normal=$(tput sgr0)                 # Text style normal

Print_logo() {
    echo -e "\e[33m         __           _       _        "
    echo -e "\e[33m /\ /\  / _\ ___ _ __(_)_ __ | |_ ___ \e[97;1m{\e[1;33mv0.3#alpha\e[0m\e[97;1m}\e[0m"
    echo -e "\e[33m/ / \ \ \ \ / __| '__| | '_ \| __/ __| "
    echo -e "\e[33m\ \_/ / _\ \ (__| |  | | |_) | |_\__ \ "
    echo -e "\e[33m \___/  \__/\___|_|  |_| .__/ \__|___/ "
    echo -e "\e[33m                       |_|             \e[39;4mhttps://uscripts.org\e[0m"
    printf "$(date) \n"
    Footer
}
Header(){                  # Print Headers inside functions
    local h="$@"
    echo " +-----------------------------------------------------------------------"
    echo " | ${h}"
    echo " +-----------------------------------------------------------------------"
}
Footer() {
    echo ""
}
Noparam() {                  # Print message when no parameter
    Print_logo
    echo "error:    no parameters"
    echo "          --help or -h parameter for help"
    echo "Example:"
    echo "          ./uscripts -h"
    echo "          ./uscripts --help"
    echo "          ./us -h"
    echo "          ./us --help" 
    Footer
    Footer
echo "https://uscripts.org not working yet!"
echo "Please visit https://github.com/dan1988dan/uscripts"
}
Wrongparam() {               # Print message when wrong parameter
    printf "error:  incorrenct parameter "
}
Version() {
    echo -e "Program version: v0.3#alpha"
}
About() {
    echo '"UScripts" - means - "Usefull Scripts"'
    echo -e "License: Open Source"
}
Help() {                   # Help message
    Print_logo
    printf 'Usage:  us.sh [option] [option=value]
Example:  ./us -i -d -w -sC=60


OPTIONS:
-----------------  
-u    --uptime             Tell how long the system has been running
-i    --systeminfo         System info and public ip address
-hn   --handwarename       Find the server hardware name and model
-fe   --firmwareerrors     Show all firmware errors

-w    --who                Who is online
-l    --last=[VALUE]       Last logged in users (e.g. "last=10") - [[default prints everything]]

-t    --checktor           Check are you using Tor or not
-p    --ping=[URL]         Ping (e.g. "ping=redhat.com") - [[default URL is "google.com"]]
-I    --checkip            Public ip
-d    --dns                Hostname and dns info and local ip

-du   --discusage          Disc usage
-ds   --discusages         Disc usage (short)

-ci   --cpuinfo            Print the cpu information
-ca   --cpuarchitecture    Display information about the cpu architecture
-cl   --cpuaverage         Check the cpu load average
-cs   --cpustat            Check the cpu stat

-vm   --virtualmemory      Report virtual memory statistics
-mi   --memoryinfo         Print the memory information

-ss   --checkswap          Check your current swappiness setting
-sc   --changeswap=[VALUE] Change your current swappiness setting (e.g. "changeswap=60")
-se   --swap=enable        Enable swap
-sd   --swap=disable       Disable swap

-k    --kernel             Check kernel version
-ks   --showkernels        Show old kernels list
-kr   --removekernels      Remove old kernels

-tc   --checkthumbnail     Check thumbnail cache
-tr   --removethumbnail    Remove thumbnail cache
-sf   --subfolders         Tell you how many subfolders are here
-uu   --aptupdate          Update and upgrade system, after remove all unused dependecies

      --chmod              chmod permissions table
      --etcpasswd          etc/passwd explanation
      --etcshadow          etc/shadow explanation
      --movingcli          moving cli shortcuts

-h    --help               Show basic help message and exit
-hh   --hhelp              Show advanced help message and exit
-V    --version            Print program version and exit
-U    --update             Update program to new version
-A    --about              About...'
    Footer
}
Hhelp() {                   # Help message
    Print_logo
    printf 'Usage:  us.sh [option] [option=value]
Example:  ./us -i -d -w -sC=60


   SYSTEM INFO:
-----------------  
-u    --uptime             Tell how long the system has been running
                                [=pretty]   wypisanie czasu działania w ładnym formacie
                                [=since]   system włączony od
-i    --systeminfo         System info and public ip address
                                [=id]   show distributor ID
                                [=description]   show description of this distribution
                                [=release]   show release number of this distribution
                                [=codename]   show code name of this distribution
                                [=all]   show all of the above information
                                [=short]   show requested information in short format
-hn   --handwarename       Find the server hardware name and model
-fe   --firmwareerrors     Show all firmware errors


     USERS:
-----------------  
-w    --who                Who is online
-l    --last=[VALUE]       Last logged in users (e.g. "last=10") - [[default prints everything]]


   NETWORKING:
-----------------         
-t    --checktor           Check are you using Tor or not
-p    --ping=[URL]         Ping (e.g. "ping=redhat.com") - [[default URL is "google.com"]]
-I    --checkip            Public ip
-d    --dns                Hostname and dns info and local ip


     DISCS:
-----------------   
-du   --discusage          Disc usage
-ds   --discusages         Disc usage (short)


      CPU:
-----------------         
-ci   --cpuinfo            Print the cpu information
-ca   --cpuarchitecture    Display information about the cpu architecture
-cl   --cpuaverage         Check the cpu load average
-cs   --cpustat            Check the cpu stat


     MEMORY:
-----------------         
-vm   --virtualmemory      Report virtual memory statistics
-mi   --memoryinfo         Print the memory information


      SWAP:
-----------------         
-ss   --checkswap          Check your current swappiness setting
-sc   --changeswap=[VALUE] Change your current swappiness setting (e.g. "changeswap=60")
-se   --swap=enable        Enable swap
-sd   --swap=disable       Disable swap


     KERNEL:
-----------------         
-k    --kernel             Check kernel version
-ks   --showkernels        Show old kernels list
-kr   --removekernels      Remove old kernels


      OTHER:
-----------------         
-tc   --checkthumbnail     Check thumbnail cache
-tr   --removethumbnail    Remove thumbnail cache
-sf   --subfolders         Tell you how many subfolders are here
-uu   --aptupdate          Update and upgrade system, after remove all unused dependecies


  CHEAT SHEET:              -CS  --cheatsheet
-----------------         
      --chmod              chmod permissions table
      --etcpasswd          etc/passwd explanation
      --etcshadow          etc/shadow explanation
      --movingcli          moving cli shortcuts


    PROGRAM:                -VA  --versionabout
-----------------         
-h    --help               Print basic help message and exit
-hh   --hhelp              Print help message in list
-V    --version            Print program version and exit
-U    --update             Update program to new version
-A    --about              About...'
    Footer
}
Chmod_table() {
    local red="\e[0;91m"
    local reset="\e[0m"
    Header "chmod  -  Permissions Table:"
echo -e "
         |  U   G   O            ${red}Chmods:${reset}
          -----------            777 = rwxrwxrwx
 (r)ead  |  4   4   4            755 = rwxr-xr-x
 (w)rite |  2   2   2            644 = rw-r--r--
e(x)ecute|  1   1   1            700 = rwx------
         |                       750 = rwxr-x---

U=users   G=group   O=others"
Footer
}
Etcpasswd() {
    Header "/etc/passwd: "
    echo "
mark: x: 1001: 1001: mark,,,: /home/mark: /bin/bash
  |   |   |     |     |             |       |
  |   |   |     |     |             |       +-> 7. Login shell
  |   |   |     |     |             +---------> 6. Home directory
  |   |   |     |     +-----------------------> 5. GECOS (Full info of user or app)
  |   |   |     +-----------------------------> 4. GID (Group ID)
  |   |   +-----------------------------------> 3. UID (User ID)
  |   +---------------------------------------> 2. Password
  +-------------------------------------------> 1. Username"
    Footer
}
Etcshadow() {
    Header "/etc/shadow: "
    echo "
mark: #6#: 17736: 0: 99999: 7: : : :
  |    |     |    |    |     | | | |
  |    |     |    |    |     | | | +---> 9. Unused
  |    |     |    |    |     | | +-----> 8. Expiration date
  |    |     |    |    |     | +-------> 7. Inactivity period
  |    |     |    |    |     +---------> 6. Warning period
  |    |     |    |    +---------------> 5. Maximum password age
  |    |     |    +--------------------> 4. Minimum password age
  |    |     +-------------------------> 3. Last password age
  |    +-------------------------------> 2. Encrypted password
  +------------------------------------> 1. Username"
    Footer
}
Movingcli() {
    Header "Moving CLI: "
    echo "
        Ctrl-A          Ctrl-E              |
   <-------------- ----------------->       |
           Alt-B      Alt-F                 | Moving
        <--------- ----------->             |
            Ctrl-B Ctrl-F                   |
                <- ->
$  cp   m y f i ( l ) e n a m e   dir
        <--------- ----------->             
          Ctrl-W      Alt-D                 | Erasing
   <-------------- ----------------->       |
        Ctrl-U          Ctrl-K              "
    Footer
}


if [ "$1" = "" ]; then              # Option no parameter
    Noparam
fi

while [ ! -z "$1" ]; do             # Options
#for i in "$@"
#do
case $1 in
    --help|-h)
        shift
        Help
        ;;
    --hhelp|-hh)
        shift
        Hhelp
        ;;
    --checktor|-t)
        shift
        Header " Check Tor: "
        curl -sS https://check.torproject.org | grep --color -m1 'Congratulations.\|This browser\|is configured\|to use\|Tor.\|Sorry.\|You are\|not using'
        Footer
        ;; 

#    Ping() {
#    Header " Ping: "
#    ping google.com -c 8
#    Footer
#    }

#    Ping2() {
#    Header " Ping: "
#    ping $ping_url -c 8
#    Footer 
#    }

#   --last=*|-l=*)
#       last_number="${1#*=}"
#       shift
#       Header " Last logged in users: "
#       last -n $last_number
#       Footer
#       ;;
    --ping|-p|--ping=|-p=)
        shift
            if [ "$1" ]; then
                Header " Ping: "
                ping $1 $2 $3                       #DOKOŃCZYĆ PING. PROBLEM Z WYBOREM OPCJI -c (ile razy ma wyświetlić ping)
            else                                    #ZAMIENIEĆ -c na time=
                ping google.pl
            fi
        ;;
    --ping=*|-p=*)
        ping_value="${1#*=}"
        time_value="-c${2#*=}"
        shift
        shift
        Header " Ping: "
        ping $ping_value $time_value
        ;;
    --checkip|-I)
        shift
        Header " ip address: "
        curl -sS ifconfig.me
        echo -e "\n"
        ;;
    --uptime|-u)
        shift
        Header "Uptime: "
        uptime $2
        Footer
        ;;
    --uptime=*)
        uptime_value="--${1#*=}"
        shift
        Header "Uptime: "
        uptime $uptime_value
        Footer
        ;;
    --systeminfo|-i)
        shift
        # local LSB=/usr/bin/lsb_release            # Path to lsb_release script (system info)
        Header " System info: "
        lsb_release -cdir
        Footer
        ;;
    --kernel|-k)
        shift
        Header " Kernel version: "
        uname -v
        Footer
        ;;
    --dns|-d)
        shift
        Header " Hostname and DNS info and ip: "
        dnsips=$(sed -e '/^$/d' /etc/resolv.conf | awk '{if (tolower($1)=="nameserver") print $2}')
        echo "Hostname : $(hostname -s)"
        echo "DNS domain : $(hostname -d)"
        echo "Fully qualified domain name : $(hostname -f)"
        echo "Network address (IP) : $(hostname -i)"
        echo "DNS name servers (DNS IP) : ${dnsips}"
        Footer
        ;;
    --who|-w)
        shift
        Header " Who is online: "
        who -H
        Footer
        ;;
    # Last_logged_in_users() {
    # Header " Last logged in users: "
    # last -n $last_number
    # Footer
    # }
    --last=*|-l=*)
        last_number="${1#*=}"
        shift
        Header " Last logged in users: "
        last -n $last_number
        Footer
        ;;
    --last|-l)
        shift
        Header " Last logged in users: "
        last
        Footer
        ;;
    --discusage|-du)
        shift
        Header " Disc usage: "
        df --total -H
        Footer
        ;;
    --discuseges|-ds)
        shift
        Header " Disc usage short: "
        df / -H
        Footer
        ;;
    --showkernels|-ks)
        shift
        Header "Show old kernels list: "
        sudo dpkg --list 'linux-image*'
        Footer
        ;;
    --removekernels|-kr)
        shift
        Header "Remove old kernels: "
        sudo apt-get remove linux-image-VERSION
        Footer
        ;;
    --firmwareerrors|-fe)
        shift
        Headers "Firmware errors: "
        dmesg | grep -i -P --colour='never' 'firmware'
        Footer
        ;;
    --virtualmemory|-vm)
        shift
        Header "Virtual memory statistics: "
        vmstat
        Footer
        ;;
    --memoryinfo|-mi)
        shift
        Header "Memory information: "
        cat /proc/meminfo
        Footer
        ;;
    --cpuinfo|-ci)
        shift
        Header "Cpu information: "
        cat /proc/cpuinfo
        Footer
        ;;
    --cpuarchitecture|-ca)
        shift
        Header "Information about the CPU architecture: "
        lscpu
        Footer
        ;;
    --cpuaverage|-cl)
        shift
        Header "Cpu load average: "
        cat /proc/loadavg
        Footer
        ;;
    --cpustat|-cs)
        shift
        Header "Cpu stat: "
        cat /proc/stat
        Footer
        ;;
    --hardwarename|-hn)
        shift
        Header "Server hardware name and model: "
        sudo dmidecode | grep -A3 '^System Information'
        Footer
        ;;
    --checkthumbnails|-tc)
        shift
        Header "Check thumbnail cache: "
        du -sh ~/.cache/thumbnails
        Footer
        ;;
    --removethumbnails|-tr)
        shift
        Header "Remove/Clean thumbnail cache: "
        sudo rm -rf ~/.cache/thumbnails/*
        Footer
        ;;
    --chmod|-ch)
        shift
        Chmod_table
        ;;
    --etcpasswd|-ep)
        shift
        Etcpasswd
        ;;
    --etcshadow|-es)
        shift
        Etcshadow
        ;;
    --movingcli)
        shift
        Movingcli
        ;;
    --subfolders|-sf)
        shift
        Header " Subfolders: "
        echo "Liczba podkatalogów to:  " $(ls -al | grep '^d' | tail -n +3 | wc -l)
        Footer
        ;;
    --aptupdate|-u)
        shift
        Header " System update: "
        sleep 2
        echo -e "Updating and upgrading system.... \n"
        sleep 2
        sudo apt update 
        sudo apt upgrade 
        sudo apt autoremove
        sudo apt remove --purge
        Header " DONE."
        Footer
        ;;
    --checkswap|-ss)
        shift
        Header "Your current swappiness setting: "
        cat /proc/sys/vm/swappiness
        Footer
        ;;
    --changeswap=*|-sc=*)
        swap_value="${1#*=}"
        shift
        Header "Change your current swappiness setting: "
        #echo "current value: " 
        #cat /proc/sys/vm/swappiness
        #echo "enter value: "
        #read xvalue
        sudo sysctl vm.swappiness=$swap_value
        Footer
        ;;
    --changeswap|-sc)
        shift
        Header "Change your current swappiness setting: "
        sudo sysctl vm.swappiness
        Footer
        ;;
    --swap=enable|--swapenable|--swap=on|--swapon|-se)
        swapon=on
        shift
        Header "Enable swap: "
        sudo swap$swapon -a
        Footer
        ;;
    --swap=disable|--swapdisable|--swap=off|--swapoff|-sd)
        swapoff=off
        shift
        Header "Disable swap: "
        sudo swap$swapoff -a
        Footer
        ;;
    --version|-V)
        shift
        Version
        ;;
    --update|-U)
        shift
        echo "Update option is not available yet"
        echo "Visit https://uscripts.org  or  https://github.com/dan1988dan/uscripts"
        ;;
    --about|-A)
        shift
        About
        ;;
    -CS|--cheatsheet)
        shift
        Chmod_table
        Etcpasswd
        Etcshadow
        Movingcli
        ;;
    -VA|--versionabout)
        shift
        Version
        About
        ;;
    *)
        shift
        Wrongparam
        exit
        ;;
esac
done
