#!/bin/bash

############################## U SCRIPTS ###################################
##                  DanielDAN - danielolszyk1988@gmail.com                ##
##                      This program is Open Source                       ##
############################################################################


# bold=$(tput bold)                   # Text style bold
# normal=$(tput sgr0)                 # Text style normal

Print_logo() {
    echo -e "\e[33m         __           _       _        "
    echo -e "\e[33m /\ /\  / _\ ___ _ __(_)_ __ | |_ ___ \e[97;1m{\e[1;33mv0.3#alpha\e[0m\e[97;1m}\e[0m"
    echo -e "\e[33m/ / \ \ \ \ / __| '__| | '_ \| __/ __| "
    echo -e "\e[33m\ \_/ / _\ \ (__| |  | | |_) | |_\__ \ "
    echo -e "\e[33m \___/  \__/\___|_|  |_| .__/ \__|___/ "
    echo -e "\e[33m                       |_|             \e[39;4mhttps://uscripts.org\e[0m"
    printf "$(date) \n"
    Footer
}
Header(){                  # Print Headers inside functions
    local h="$@"
    echo " +-----------------------------------------------------------------------"
    echo " | ${h}"
    echo " +-----------------------------------------------------------------------"
}
Footer() {
    echo ""
}
Noparam() {                  # Print message when no parameter
    Print_logo
    echo "error:    no parameters"
    echo "          --help or -h parameter for help"
    echo "Example:"
    echo "          ./uscripts -h"
    echo "          ./uscripts --help"
    echo "          ./us -h"
    echo "          ./us --help"
    Footer
}
Wrongparam() {               # Print message when wrong parameter
    printf "error:  incorrenct parameter "
}
Help() {                   # Help message
    Print_logo
    echo "Usage:  us.sh [option] [option=value]"
    echo "Example:  ./us -i -d -w -sC=60"
    echo ""
    echo "OPTIONS:"
    echo "--------"
    echo "-t    --checktor           Check are you using Tor or not"
    echo '-p    --ping=[URL]         Ping (e.g. "ping=redhat.com") - [[default URL is "google.com"]]'
    echo "-I    --checkip            Public ip"
    echo "-u    --uptime             Tell how long the system has been running"
    echo "-i    --systeminfo         System info and public ip address"
    echo "-k    --kernel             Check kernel version"
    echo "-d    --dns                Hostname and dns info and local ip"
    echo "-w    --who                Who is online"
    echo '-l    --last=[VALUE]       Last logged in users (e.g. "last=10") - [[default prints everything]]'
    echo "-du   --discusage          Disc usage"
    echo "-ds   --discusages         Disc usage (short)"
    echo "-ks   --showkernels        Show old kernels list"
    echo "-kr   --removekernels      Remove old kernels"
    echo "-fe   --firmwareerrors     Show all firmware errors"
    echo "-vm   --virtualmemory      Report virtual memory statistics"
    echo "-mi   --memoryinfo         Print the memory information"
    echo "-ci   --cpuinfo            Print the cpu information"
    echo "-ca   --cpuarchitecture    Display information about the cpu architecture"
    echo "-cl   --cpuaverage         Check the cpu load average"
    echo "-cs   --cpustat            Check the cpu stat"
    echo "-hn   --handwarename       Find the server hardware name and model"
    echo "-ss   --checkswap          Check your current swappiness setting"
    echo '-sc   --changeswap=[VALUE] Change your current swappiness setting (e.g. "changeswap=60")'
    echo "-se   --swap=enable        Enable swap"
    echo "-sd   --swap=disable       Disable swap"
    echo "-tc   --checkthumbnail     Check thumbnail cache"
    echo "-tr   --removethumbnail    Remove thumbnail cache"
    echo "-sf   --subfolders         Tell you how many subfolders are here"
    echo "-uu   --aptupdate          Update and upgrade system, after remove all unused dependecies"
    echo -e "-----------------         ------------------------------------
    CHEAT SHEET:"
    echo "-ch   --chmod              chmod permissions table"
    echo "-ep   --etcpasswd          etc/passwd explanation"
    echo "-es   --etcshadow          etc/shadow explanation"
    echo "      --movingcli          moving cli shortcuts"
    echo -e "-----------------         ------------------------------------
    PROGRAM:"
    echo "-h    --help               Print basic help message and exit"
    echo "-V    --version            Print program version and exit"
    echo "-U    --update             Update program to new version"
    echo "-A    --about              About..."
    Footer
}
#Ping() {
#    Header " Ping: "
#    ping google.com -c 8
#    Footer
#}
#Ping2() {
#    Header " Ping: "
#    ping $ping_url -c 8
#    Footer
#}
Chmod_table() {
    local red="\e[0;91m"
    local reset="\e[0m"
    Header "chmod  -  Permissions Table:"
echo -e "
         |  U   G   O            ${red}Chmods:${reset}
          -----------            777 = rwxrwxrwx
 (r)ead  |  4   4   4            755 = rwxr-xr-x
 (w)rite |  2   2   2            644 = rw-r--r--
e(x)ecute|  1   1   1            700 = rwx------
         |                       750 = rwxr-x---

U=users   G=group   O=others"
Footer
}
Etcpasswd() {
    Header "/etc/passwd: "
    echo "
mark: x: 1001: 1001: mark,,,: /home/mark: /bin/bash
  |   |   |     |     |             |       |
  |   |   |     |     |             |       +-> 7. Login shell
  |   |   |     |     |             +---------> 6. Home directory
  |   |   |     |     +-----------------------> 5. GECOS (Full info of user or app)
  |   |   |     +-----------------------------> 4. GID (Group ID)
  |   |   +-----------------------------------> 3. UID (User ID)
  |   +---------------------------------------> 2. Password
  +-------------------------------------------> 1. Username"
    Footer
}
Etcshadow() {
    Header "/etc/shadow: "
    echo "
mark: #6#: 17736: 0: 99999: 7: : : :
  |    |     |    |    |     | | | |
  |    |     |    |    |     | | | +---> 9. Unused
  |    |     |    |    |     | | +-----> 8. Expiration date
  |    |     |    |    |     | +-------> 7. Inactivity period
  |    |     |    |    |     +---------> 6. Warning period
  |    |     |    |    +---------------> 5. Maximum password age
  |    |     |    +--------------------> 4. Minimum password age
  |    |     +-------------------------> 3. Last password age
  |    +-------------------------------> 2. Encrypted password
  +------------------------------------> 1. Username"
    Footer
}
Movingcli() {
    Header "Moving CLI: "
    echo "
        Ctrl-A          Ctrl-E              |
   <-------------- ----------------->       |
           Alt-B      Alt-F                 | Moving
        <--------- ----------->             |
            Ctrl-B Ctrl-F                   |
                <- ->
$  cp   m y f i ( l ) e n a m e   dir
        <--------- ----------->             
          Ctrl-W      Alt-D                 | Erasing
   <-------------- ----------------->       |
        Ctrl-U          Ctrl-K              "
    Footer
}


if [ "$1" = "" ]; then              # Option no parameter
    Noparam
fi

while [ ! -z "$1" ]; do             # Options
#for i in "$@"
#do
case $1 in
    --help|-h)
        shift
        Help
        ;;
    --checktor|-t)
        shift
        Header " Check Tor: "
        curl -sS https://check.torproject.org | grep --color -m1 'Congratulations.\|This browser\|is configured\|to use\|Tor.\|Sorry.\|You are\|not using'
        Footer
        ;; 
    --ping|-p)
        shift
            if [ "$1" ]; then
                Header " Ping: "
                ping $1
            else
                ping google.pl
            fi
        ;;
    --checkip|-I)
        shift
        Header " ip address: "
        curl -sS ifconfig.me
        echo -e "\n"
        ;;
    --uptime|-u)
        shift
        Header "Uptime: "
        uptime
        Footer
        ;;
    --systeminfo|-i)
        shift
        # local LSB=/usr/bin/lsb_release            # Path to lsb_release script (system info)
        Header " System info: "
        lsb_release -cdir
        Footer
        ;;
    --kernel|-k)
        shift
        Header " Kernel version: "
        uname -v
        Footer
        ;;
    --dns|-d)
        shift
        Header " Hostname and DNS info and ip: "
        local dnsips=$(sed -e '/^$/d' /etc/resolv.conf | awk '{if (tolower($1)=="nameserver") print $2}')
        echo "Hostname : $(hostname -s)"
        echo "DNS domain : $(hostname -d)"
        echo "Fully qualified domain name : $(hostname -f)"
        echo "Network address (IP) : $(hostname -i)"
        echo "DNS name servers (DNS IP) : ${dnsips}"
        Footer
        ;;
    --who|-w)
        shift
        Header " Who is online: "
        who -H
        Footer
        ;;
    # Last_logged_in_users() {
    # Header " Last logged in users: "
    # last -n $last_number
    # Footer
    # }
    --last=*|-l=*)
        last_number="${1#*=}"
        shift
        Header " Last logged in users: "
        last -n $last_number
        Footer
        ;;
    --last|-l)
        shift
        Header " Last logged in users: "
        last
        Footer
        ;;
    --discusage|-du)
        shift
        Header " Disc usage: "
        df --total -H
        Footer
        ;;
    --discuseges|-ds)
        shift
        Header " Disc usage short: "
        df / -H
        Footer
        ;;
    --showkernels|-ks)
        shift
        Header "Show old kernels list: "
        sudo dpkg --list 'linux-image*'
        Footer
        ;;
    --removekernels|-kr)
        shift
        Header "Remove old kernels: "
        sudo apt-get remove linux-image-VERSION
        Footer
        ;;
    --firmwareerrors|-fe)
        shift
        Headers "Firmware errors: "
        dmesg | grep -i -P --colour='never' 'firmware'
        Footer
        ;;
    --virtualmemory|-vm)
        shift
        Header "Virtual memory statistics: "
        vmstat
        Footer
        ;;
    --memoryinfo|-mi)
        shift
        Header "Memory information: "
        cat /proc/meminfo
        Footer
        ;;
    --cpuinfo|-ci)
        shift
        Header "Cpu information: "
        cat /proc/cpuinfo
        Footer
        ;;
    --cpuarchitecture|-ca)
        shift
        Header "Information about the CPU architecture: "
        lscpu
        Footer
        ;;
    --cpuaverage|-cl)
        shift
        Header "Cpu load average: "
        cat /proc/loadavg
        Footer
        ;;
    --cpustat|-cs)
        shift
        Header "Cpu stat: "
        cat /proc/stat
        Footer
        ;;
    --hardwarename|-hn)
        shift
        Header "Server hardware name and model: "
        sudo dmidecode | grep -A3 '^System Information'
        Footer
        ;;
    --checkswap|-ss)
        shift
        Header "Your current swappiness setting: "
        cat /proc/sys/vm/swappiness
        Footer
        ;;
    --changeswap=*|-sc=*)
        swap_value="${1#*=}"
        shift
        Header "Change your current swappiness setting: "
        #echo "current value: " 
        #cat /proc/sys/vm/swappiness
        #echo "enter value: "
        #read xvalue
        sudo sysctl vm.swappiness=$swap_value
        Footer
        ;;
    --changeswap|-sc)
        shift
        Header "Change your current swappiness setting: "
        sudo sysctl vm.swappiness
        Footer
        ;;
    --swap=enable|--swapenable|--swap=on|--swapon|-se)
        swapon=on
        shift
        Header "Enable swap: "
        sudo swap$swapon -a
        Footer
        ;;
    --swap=disable|--swapdisable|--swap=off|--swapoff|-sd)
        swapoff=off
        shift
        Header "Disable swap: "
        sudo swap$swapoff -a
        Footer
        ;;
    --checkthumbnails|-tc)
        shift
        Header "Check thumbnail cache: "
        du -sh ~/.cache/thumbnails
        Footer
        ;;
    --removethumbnails|-tr)
        shift
        Header "Remove/Clean thumbnail cache: "
        sudo rm -rf ~/.cache/thumbnails/*
        Footer
        ;;
    --chmod|-ch)
        shift
        Chmod_table
        ;;
    --etcpasswd|-ep)
        shift
        Etcpasswd
        ;;
    --etcshadow|-es)
        shift
        Etcshadow
        ;;
    --movingcli)
        shift
        Movingcli
        ;;
    --subfolders|-sf)
        shift
        Header " Subfolders: "
        echo "Liczba podkatalogów to:  " $(ls -al | grep '^d' | tail -n +3 | wc -l)
        Footer
        ;;
    --aptupdate|-u)
        shift
        Header " System update: "
        sleep 2
        echo -e "Updating and upgrading system.... \n"
        sleep 2
        sudo apt update 
        sudo apt upgrade 
        sudo apt autoremove
        sudo apt remove --purge
        Header " DONE."
        Footer
        ;;
    --version|-V)
        shift
        echo -e "Program version: v0.3#alpha"
        ;;
    --update|-U)
        shift
        echo "This option is not available yet"
        echo "Visit https://uscripts.org  or  https://github.com/dan1988dan/uscripts"
        ;;
    --about|-A)
        shift
        echo '"UScripts" - means - "Usefull Scripts"'
        echo -e "License: Open Source"
        ;;
    *)
        shift
        Wrongparam
        exit
        ;;
esac
done